---
- name: Setup influxDb
  gather_facts: no
  hosts: influxdb
  vars:
    - influxdb_port: 8086
  roles:
    - influxdb

- name: Setup selenoid and telegraf
  hosts: selenoid-node
  roles:
    - selenoid
  vars:
    - telegraf: true
    - selenoid_url: "http://localhost"
    - influxdb_url: "http://localhost"
    - influxdb_port: 8086
    - selenoid_browsers:
      - name: "chrome"
        default: "78.0"
        versions:
          - "78.0"
      - name: "firefox"
        default:  "70.0"
        versions:
          - "70.0"

- name: Setup selenoid-ui
  gather_facts: no
  hosts: selenoid-ui
  vars:
    - selenoid_url: "http://localhost"
    - selenoid_ui_port: 8081
  roles:
    - selenoid-ui
