---
- name: InfluxDb | Check influxdb container exist
  shell: 'docker ps -aq --filter "name={{ item }}"'
  with_items:
    - 'influxdb'
  register: found_containers

- name: InfluxDb | Remove influxdb container if exist
  shell: 'docker stop {{ item.item }} && docker rm -fv {{ item.item }}'
  with_items: '{{ found_containers.results }}'
  when: item.stdout

- name: Start influxdb
  docker_container:
    image: influxdb:alpine
    name: influxdb
    state: started
    ports:
      - "{{ influxdb_port }}:8086"
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
    env:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_DB: "{{ influxdb_db }}"
      INFLUXDB_USER: "{{ influxdb_user }}"
      INFLUXDB_USER_PASSWORD: "{{ influxdb_user_password }}"
